### ISSUE TITLE
SPRU0.MIX is not found...

### ISSUE THREAD

**Issue by yaaaaa** [IceReaper/Earth2140#1]

**Comment by IceReaper** [comment]
Ofcourse, you need the game files

**Comment by yaaaaa** [comment]
Witch version of Earth 2140 exist SPRU0.MIX file? in my installation of this game it not exist too...

**Comment by IceReaper** [comment]
Its packed in a .WD file. The required WD files are listed in the mod.yaml:
https://github.com/IceReaper/Earth2140/blob/master/mods/e2140/mod.yaml#L35
